### PR TITLE
Web editor functionblock integration

### PR DESCRIPTION
**Pull request by shiv12095**
cc @aedelmann

### CODE REVIEW

**Comment by aedelmann** [comment]
I saw, you also registered the function block editor servlet under /xtext-service. Does this not clash with the current info model servlet ?

**Comment by shiv12095** [comment]
Although both servlets are registered under /xtext-service, the function block servlet should not clash since it has not yet been invoked / instantiated in the devtool. I was planning to change the servlet mappings once I create the function block servlet in devtool.

**Comment by aedelmann** [comment]
I see. Looking forward to that integration in the devtool :)

**Comment by aedelmann** [comment]
Hi Shiv, 

the problem with function block tests has been resolved. Please rebase with latest from eclipse/vorto.

Cheers, Alex

**Pull request merged**
